apiVersion: v1
kind: Service
metadata:
  name: {{ include "bulkhead.fullname" . }}-compute
  labels:
    {{- include "bulkhead.labels" . | nindent 4 }}
    app.kubernetes.io/component: compute
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "bulkhead.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: compute
