apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulkhead.fullname" . }}-secret
  labels:
    {{- include "bulkhead.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "bulkhead.databaseUrl" . | quote }}
